service: CPULoadTest

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  memorySize: ${opt:mSize}
  timeout: 6
  profile: staging

package:
 include:
   - cpuload

functions:
  sqrt:
   name: CPULoadTest-dev-sqrt-${opt:mSize}
   handler: sqrt/sqrt
  sleep:
    name: CPULoadTest-dev-sleep-${opt:mSize}
    handler: sleep/sleep
  goroutine:
    name: CPULoadTest-dev-goroutine-${opt:mSize}
    handler: goroutine/goroutine